# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trackfw < Formula
  desc "Governed software delivery framework: ADR → REQ → ROADMAP → kanban"
  homepage "https://github.com/kgsaran/trackfw"
  version "4.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kgsaran/trackfw/releases/download/v4.0.0/trackfw_4.0.0_darwin_amd64.tar.gz"
      sha256 "1cac4b32c56f3a9073d1838290610f64362df2b8bcbb22f941b791b17798524e"

      define_method(:install) do
        bin.install "trackfw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kgsaran/trackfw/releases/download/v4.0.0/trackfw_4.0.0_darwin_arm64.tar.gz"
      sha256 "1931ec07adbfb2c3ee7fcd29201d972923006e2e2cb972c5bf785f9cd4eb2f84"

      define_method(:install) do
        bin.install "trackfw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kgsaran/trackfw/releases/download/v4.0.0/trackfw_4.0.0_linux_amd64.tar.gz"
      sha256 "41c8e1823c261f9d874f030c5f297b710dc781d830a7760b2a5b70e684b891f5"
      define_method(:install) do
        bin.install "trackfw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kgsaran/trackfw/releases/download/v4.0.0/trackfw_4.0.0_linux_arm64.tar.gz"
      sha256 "7f84ca13a4ce708e16462abfe76b8df502fdaf9e3651b8e443531548ecf94b1d"
      define_method(:install) do
        bin.install "trackfw"
      end
    end
  end

  test do
    assert_match "trackfw", shell_output("#{bin}/trackfw version")
  end
end
