# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trackfw < Formula
  desc "Governed software delivery framework: ADR → REQ → ROADMAP → kanban"
  homepage "https://github.com/kgsaran/trackfw"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kgsaran/trackfw/releases/download/v0.1.3/trackfw_0.1.3_darwin_amd64.tar.gz"
      sha256 "2732842da7fb5fc1d86d79105255f66d01fa77bd7c3c54e5d86292234bb81723"

      define_method(:install) do
        bin.install "trackfw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kgsaran/trackfw/releases/download/v0.1.3/trackfw_0.1.3_darwin_arm64.tar.gz"
      sha256 "c71c0c7e053f85d26de86bfe9cba88a133303e6006ef73064d4df6a71e8b1be7"

      define_method(:install) do
        bin.install "trackfw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kgsaran/trackfw/releases/download/v0.1.3/trackfw_0.1.3_linux_amd64.tar.gz"
      sha256 "cc3f847c8248f1ef2eb35ad1f1de7978116c08c45264e5a4515d213499744973"
      define_method(:install) do
        bin.install "trackfw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kgsaran/trackfw/releases/download/v0.1.3/trackfw_0.1.3_linux_arm64.tar.gz"
      sha256 "8ff4c55a5abf9f5fc8758eff92797e6c8826c881caa51e30956720028eaa7562"
      define_method(:install) do
        bin.install "trackfw"
      end
    end
  end

  test do
    assert_match "trackfw", shell_output("#{bin}/trackfw version")
  end
end
