# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trackfw < Formula
  desc "Governed software delivery framework: ADR → REQ → ROADMAP → kanban"
  homepage "https://github.com/kgsaran/trackfw"
  version "7.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kgsaran/trackfw/releases/download/v7.2.0/trackfw_7.2.0_darwin_amd64.tar.gz"
      sha256 "ee34d409ae6970b6b474903d56717077ce3c488cfb29395bfa3c7c9af5662cf4"

      define_method(:install) do
        bin.install "trackfw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kgsaran/trackfw/releases/download/v7.2.0/trackfw_7.2.0_darwin_arm64.tar.gz"
      sha256 "8ad9e250ebb7372d3996d7ce25017942e1ec09511756233cd09d2ec47701bca7"

      define_method(:install) do
        bin.install "trackfw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kgsaran/trackfw/releases/download/v7.2.0/trackfw_7.2.0_linux_amd64.tar.gz"
      sha256 "cd531b939cac94afae9783aad60ff352b29357faf25566e3cc8d0e655862d7ae"
      define_method(:install) do
        bin.install "trackfw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kgsaran/trackfw/releases/download/v7.2.0/trackfw_7.2.0_linux_arm64.tar.gz"
      sha256 "f189091e62748f1c394250e0f0632b4b62d9b3297cd7e5b818403f0ebbe46f7e"
      define_method(:install) do
        bin.install "trackfw"
      end
    end
  end

  test do
    assert_match "trackfw", shell_output("#{bin}/trackfw version")
  end
end
